# -*- coding: utf-8 -*-

# assault rifles
Amprex = 'Amprex'
Soma = 'Soma'
SomaPrime = 'SomaPrime'
TelosBoltor = 'TelosBoltor'
Tonkor = 'Tonkor'

# sniper rifles

# bows
Attica = 'Attica'
Cernos = 'Cernos'
Daikyu = 'Daikyu'
Dread = 'Dread'
MK1Paris = 'MK1Paris'
MutalistCernos = 'MutalistCernos'
Paris = 'Paris'
RaktaCernos = 'RaktaCernos'
Zhuge = 'Zhuge'

# shotguns
Hek = 'Hek'
Kohm = 'Kohm'
Tigris = 'Tigris'
VaykorHek = 'VaykorHek'

# pistols
Acrid = 'Acrid'
Afuris = 'Afuris'
Akbolto = 'Akbolto'
Akbronco = 'Akbronco'
AkbroncoPrime = 'AkbroncoPrime'
Akjagara = 'Akjagara'
Aklato = 'Aklato'
Aklex = 'Aklex'
Akmagnus = 'Akmagnus'
Aksomati = 'Aksomati'
Akstiletto = 'Akstiletto'
AkstilettoPrime = 'AkstilettoPrime'
Akvasto = 'Akvasto'
Akzani = 'Akzani'
Angstrum = 'Angstrum'
Atomos = 'Atomos'
Azima = 'Azima'
Ballistica = 'Ballistica'
Bolto = 'Bolto'
Brakk = 'Brakk'
Bronco = 'Bronco'
BroncoPrime = 'BroncoPrime'
Castanas = 'Castanas'
Cestra = 'Cestra'
Despair = 'Despair'
Detron = 'Detron'
DexFuris = 'DexFuris'
DualCestra = 'DualCestra'
DualToxocyst = 'DualToxocyst'
Embolist = 'Embolist'
Furis = 'Furis'
Gammacor = 'Gammacor'
Hikou = 'Hikou'
HikouPrime = 'HikouPrime'
Kohmak = 'Kohmak'
Kraken = 'Kraken'
Kulstar = 'Kulstar'
Kunai = 'Kunai'
Lato = 'Lato'
LatoPrime = 'LatoPrime'
LatoVandal = 'LatoVandal'
Lex = 'Lex'
LexPrime = 'LexPrime'
Magnus = 'Magnus'
MaraDetron = 'MaraDetron'
Marelok = 'Marelok'
MK1Furis = 'MK1-Furis'
MK1Kunai = 'MK1-Kunai'
Nukor = 'Nukor'
Pyrana = 'Pyrana'
RaktaBallistica = 'RaktaBallistica'
SanctiCastanas = 'SanctiCastanas'
SecuraDualCestra = 'SecuraDualCestra'
Seer = 'Seer'
Sicarus = 'Sicarus'
SicarusPrime = 'SicarusPrime'
Sonicor = 'Sonicor'
Spectra = 'Spectra'
Spira = 'Spira'
SpiraPrime = 'SpiraPrime'
Staticor = 'Staticor'
Stug = 'Stug'
SynoidGammacor = 'SynoidGammacor'
Talons = 'Talons'
TelosAkbolto = 'TelosAkbolto'
TwinGrakatas = 'TwinGrakatas'
TwinGremlins = 'TwinGremlins'
TwinKohmak = 'TwinKohmak'
TwinVipers = 'TwinVipers'
Tysis = 'Tysis'
Vasto = 'Vasto'
VastoPrime = 'VastoPrime'
VaykorMarelok = 'VaykorMarelok'
Viper = 'Viper'
WraithTwinVipers = 'WraithTwinVipers'

# melee
Redeemer = 'Redeemer'


# rifle_mods
BaneOfX = 'BaneOfX'
CrashCourse = 'CrashCourse'
CriticalDelay = 'CriticalDelay'
CryoRounds = 'CryoRounds'
FangedFusillade = 'FangedFusillade'
FastHands = 'FastHands'
HammerShot = 'HammerShot'
HeavyCaliber = 'HeavyCaliber'
Hellfire = 'Hellfire'
HighVoltage = 'HighVoltage'
InfectedClip = 'InfectedClip'
MagazineWarp = 'MagazineWarp'
MalignantForce = 'MalignantForce'
PiercingCaliber = 'PiercingCaliber'
PiercingHit = 'PiercingHit'
PointStrike = 'PointStrike'
PrimedBaneOfX = 'PrimedBaneOfX'
PrimedFastHands = 'PrimedFastHands'
RifleAptitude = 'RifleAptitude'
RimeRounds = 'RimeRounds'
Rupture = 'Rupture'
SawtoothClip = 'SawtoothClip'
Serration = 'Serration'
Shred = 'Shred'
SpeedTrigger = 'SpeedTrigger'
SplitChamber = 'SplitChamber'
Stormbringer = 'Stormbringer'
ThermiteRounds = 'ThermiteRounds'
VileAcceleration = 'VileAcceleration'
VilePrecision = 'VilePrecision'
VitalSense = 'VitalSense'
Wildfire = 'Wildfire'

# mass_rifle_mods
TaintedMag = 'TaintedMag'

# sniper_mods
DepletedReload = 'DepletedReload'

# bow_mods
Thunderbolt = 'Thunderbolt'

# shotgun_mods
AcceleratedBlast = 'AcceleratedBlast'
AmmoStock = 'AmmoStock'
Blaze = 'Blaze'
Blunderbuss = 'Blunderbuss'
BreachLoader = 'BreachLoader'
BurdenedMagazine = 'BurdenedMagazine'
ChargedShell = 'ChargedShell'
ChillingGrasp = 'ChillingGrasp'
CleanseX = 'CleanseX'
ContagiousSpread = 'ContagiousSpread'
CriticalDeceleration = 'CriticalDeceleration'
Disruptor = 'Disruptor'
Flechette = 'Flechette'
FrailMomentum = 'FrailMomentum'
FrigidBlast = 'FrigidBlast'
FullContact = 'FullContact'
HellsChamber = 'HellsChamber'
IncendiaryCoat = 'IncendiaryCoat'
PointBlank = 'PointBlank'
PrimedPointBlank = 'PrimedPointBlank'
PrimedRavage = 'PrimedRavage'
Ravage = 'Ravage'
ScatteringInferno = 'ScatteringInferno'
SeekingFury = 'SeekingFury'
ShellShock = 'ShellShock'
ShotgunSavvy = 'ShotgunSavvy'
ShotgunSpazz = 'ShotgunSpazz'
Shredder = 'Shredder'
SweepingSerration = 'SweepingSerration'
TacticalPump = 'TacticalPump'
TaintedShell = 'TaintedShell'
ToxicBarrage = 'ToxicBarrage'
ViciousSpread = 'ViciousSpread'

# pistol_mods
Quickdraw = 'Quickdraw'
RazorShot = 'RazorShot'
Scorch = 'Scorch'
SlipMagazine = 'SlipMagazine'
StunningSpeed = 'StunningSpeed'
SureShot = 'SureShot'
TaintedClip = 'TaintedClip'
AnemicAgility = 'AnemicAgility'
BarrelDiffusion = 'BarrelDiffusion'
Bore = 'Bore'
ConcussionRounds = 'ConcussionRounds'
Convulsion = 'Convulsion'
CreepingBullseye = 'CreepingBullseye'
DeepFreeze = 'DeepFreeze'
ExpelX = 'ExpelX'
Frostbite = 'Frostbite'
Gunslinger = 'Gunslinger'
HeatedCharge = 'HeatedCharge'
HollowPoint = 'HollowPoint'
HornetStrike = 'HornetStrike'
IceStorm = 'IceStorm'
Jolt = 'Jolt'
LethalTorrent = 'LethalTorrent'
MagnumForce = 'MagnumForce'
Maim = 'Maim'
NoReturn = 'NoReturn'
PathogenRounds = 'PathogenRounds'
PistolGambit = 'PistolGambit'
PistolPestilence = 'PistolPestilence'
PrimedHeatedCharge = 'PrimedHeatedCharge'
PrimedPistolGambit = 'PrimedPistolGambit'
PrimedSlipMagazine = 'PrimedSlipMagazine'
PrimedTargetCracker = 'PrimedTargetCracker'
Pummel = 'Pummel'
TargetCracker = 'TargetCracker'

# melee_mods
AugerStrike = 'AugerStrike'
BuzzKill = 'BuzzKill'
CollisionForce = 'CollisionForce'
EnduringStrike = 'EnduringStrike'
FeverStrike = 'FeverStrike'
FocusEnergy = 'FocusEnergy'
Fury = 'Fury'
HeavyTrauma = 'HeavyTrauma'
JaggedEdge = 'JaggedEdge'
MeleeProwess = 'MeleeProwess'
MoltenImpact = 'MoltenImpact'
NorthWind = 'NorthWind'
OrganShatter = 'OrganShatter'
PressurePoint = 'PressurePoint'
PrimedHeavyTrauma = 'PrimedHeavyTrauma'
PrimedFury = 'PrimedFury'
PrimedPressurePoint = 'PrimedPressurePoint'
RendingStrike = 'RendingStrike'
ShockingTouch = 'ShockingTouch'
SmiteX = 'SmiteX'
SpoiledStrike = 'SpoiledStrike'
SunderingStrike = 'SunderingStrike'
TrueSteel = 'TrueSteel'
ViciousFrost = 'ViciousFrost'
VirulentScourge = 'VirulentScourge'
VolcanicEdge = 'VolcanicEdge'
VoltaicStrike = 'VoltaicStrike'
